texto = input("Qual o seu nome? ")
print("Seu nome é: ", texto)
texto2 = input("Qual a sua idade? ")
print("Sua idade é: ", texto2)
texto3 = input("Qual a sua altura? ")
print("Sua altura é: ", texto3)
